version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REGISTRY_URI
            - REPOSITORY_URI=$REGISTRY_URI/prime-api
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - IMAGE_URI=$REPOSITORY_URI:$COMMIT_HASH
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker image...
            - docker build -t prime-api:latest .
            - docker tag prime-api:latest $IMAGE_URI
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker push $IMAGE_URI
            - echo Updating Container Definition File...
            - sed -i "s|<%IMAGE_URI%>|$IMAGE_URI|g" containerdefinition.json
            - aws ecs register-task-definition --family prime-api-task-definition --container-definitions file://containerdefinition.json
            - TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition prime-api-task-definition  --query 'taskDefinition.taskDefinitionArn' --output text)
            - sed -i "s|<%TASK_DEFINITION_ARN%>|$TASK_DEFINITION_ARN|g" appspec.yml

artifacts:
    files: appspec.yml
